### ISSUE TITLE
Suggestion for improvement: Multiple Lines of TODOs/FIXMEs

### ISSUE THREAD

**Issue by ivanskodje** [need12648430/godot-todo#6]
Suggestion for improvement: Multiple Lines of TODOs/FIXMEs.
Avoid needing to write all the comment in one line for readability.

**Comment by need12648430** [comment]
Just tested, Tree leaf nodes don't seem to support multiline text. GDScript also does not supporting multiline comments, making this a bit of an unstable feature to add.

It would be possible to group single-line comments together, and interpret them as a singular comment until separated by an empty new-line or something - but then the difference between regular comments and TODO/FIXME comments disappears as TODO/FIXME syntax would also include regular comments as part of their syntax.

It would be an expansion of GDScript syntax rather than neatly embedding inside of it. This would require the user to consider the add-on's effect on the syntax when writing code which is something I don't think should ever occur.

**Comment by need12648430** [comment]
I have considered writing another plug-in to fill the need you seem to be addressing with TODOs. I think either a project or scene-wide scratchpad for notes would suit it a bit better. It'd allow you to not only document complex project-specific scene hierarchies but the design requirements of them (e.g. use of collision layers or explanation of exports), and any caveats stumbled across when coding.

My only concern is cluttering up the GUI, as Godot 2 doesn't allow me inject entries into to the top-level menu to tuck the less focus-demanding features out of sight until needed. I've considered the editor pane as well but it can only be handled by one registered Node type at a time and I don't want to possibly conflict with other add-ons.

If this is something that might be useful for you though we might be able to work something out if we put our heads together on it and bother the FB community enough. 🤣

**Comment by ivanskodje** [comment]
I imagine the way we would implement it, is simply by checking if there is a # on the line directly underneath the TODO line, and append that text to the TODO in the addon. Keep checking until you no longer have a # comment line. There is no need to add multi-line text, we just append it. Of course, I have no idea how it would look, so it would have to be tested to see how it adapts.

#TODO: Something something
#dark side.

Waiting for Godot 3.0 before I start messing around with the EditorPlugin to see if we can expand on the functionality to allow everything we need :)

**Comment by need12648430** [comment]
That's precisely it though, at that point the TODO is eating an additional GDScript single-line comment. That comment could have been intended to be part of the TODO, or it could have been intended to be kept separate. We can't really know which.

But yeh, I do agree on waiting for 3.0. It introduces a lot of facilities for add-on authors so the whole TODO project could stand to be reworked for it anyway.
